from .main import main_blueprint
from .admin import admin_blueprint
from .categories import categories_blueprint
from .labor import labor_blueprint
from .packaging import packaging_blueprint
from .production import production_blueprint
from .weekly_costs import weekly_costs_blueprint
from .reports import reports_blueprint
from .inventory import inventory_blueprint
from .products import products_blueprint
from .raw_materials import raw_materials_blueprint
from .premakes import premakes_blueprint
from .suppliers import suppliers_blueprint
